### ISSUE TITLE
Monitor package updates with dependabot

### ISSUE THREAD

**Issue by KevinBatdorf** [jbrooksuk/artisan.page#10]
For an enhancement if #9 merges in, you could remove the manifest file and add a composer.json file, and set up dependabot to auto run the build process when a package makes a release (I think dependabot triggers action, but not 100% sure). That way you won't have to monitor any changes, and only need to update the supported packages/ laravel versions as needed.

It might also help the build run faster as I don't think composer is currently being cached since there is no lock file.

I'm happy to implement this if you'd like. Would be good practice for me.

**Comment by jbrooksuk** [comment]
I think this is the next steps for the new multiple version support we've shipped. Not sure how to do this yet since we'd need multiple versions of Laravel...

**Comment by KevinBatdorf** [comment]
The GH action matrix should take care of looping through each Laravel version, right? You'd just have to organize everything properly.

Also, instead of relying on dependabot you could just have an action that runs every 24 hours, then the Vue app reacts to the whatever data is present.

You could probably also automate fetching something like "the latest three Laravel major versions" (maybe just parsing it from the [GitHub Api](https://api.github.com/repos/laravel/laravel/releases?per_page=100)) and then the codebase will maintain itself.

**Comment by jbrooksuk** [comment]
I've setup the CI to build every week (post release day).
