### ISSUE TITLE
Support of commands from first party packages.

### ISSUE THREAD

**Issue by FoksVHox** [jbrooksuk/artisan.page#12]
The title says all. 
It would be nice if we could see the Laravel package's Artisan commands

Just like `php artisan dusk:install`

**Comment by jbrooksuk** [comment]
Hey @FoksVHox, we're actively working on bringing support for this. See #9

**Comment by jbrooksuk** [comment]
First-party packages are now supported!

**Comment by cord** [comment]
Missing [Nova](https://nova.laravel.com/)?

**Comment by jbrooksuk** [comment]
I've now added Nova, https://artisan.page/10.x/novaaction
