### ISSUE TITLE
Add api endpoints

### ISSUE THREAD

**Issue by KevinBatdorf** [jbrooksuk/artisan.page#25]
Have you though about adding api endpoints that show available commands and descriptions?

I think if you upgrade to nuxt 3 it's built in (maybe even in nuxt 2, I just don't know).

https://v3.nuxtjs.org/guide/features/server-routes

It could then be consumed by something like Alfred or Raycast. I wrote a [Forge Raycast extension](https://www.raycast.com/KevinBatdorf/laravel-forge) and was thinking to show available artisan commands by Laravel version that can execute via the [site command](https://forge.laravel.com/api-documentation#execute-command) endpoint. 

I thought about getting the commands from the server like the build command here does, but that might be too intrusive, while an API would be perfect (or I do both and have the former be opt in).

**Comment by jbrooksuk** [comment]
I hadn't, but that would be awesome!

**Comment by KevinBatdorf** [comment]
Okay cool. I'll look into it and follow up with some ideas
