### ISSUE TITLE
Support of commands from third party packages.

### ISSUE THREAD

**Issue by adampatterson** [jbrooksuk/artisan.page#26]
I know this could get out of control, but packages like Livewire or IDE helper would be nice to see.

**Comment by jbrooksuk** [comment]
Livewire and Inertia are now included.

**Comment by adampatterson** [comment]
@jbrooksuk I'd like to consider adding Filament commands. It looks like you use a JSON file but do you have a process for extracting the commands and generating the JSON?

I might attempt this.

**Comment by jbrooksuk** [comment]
I'm not really sure we should add any non-first-party packages to be honest. Happy to have my mind changed though.

**Comment by adampatterson** [comment]
haha, I agree. It's a slippery slope
