### ISSUE TITLE
Dynamic version tracking

### ISSUE THREAD

**Issue by KevinBatdorf** [jbrooksuk/artisan.page#31]
If you remember the [api variety](https://github.com/KevinBatdorf/artisan-api) I made, I added some updates to the workflow job to dynamically fetch Laravel versions. This way the repo is (hopefully) future proof when new Laravel versions are released. It also manages the PHP dependency.

The code looks like:

```sh
curl -s https://packagist.org/packages/laravel/laravel.json \
| jq -r '.package.versions[] | select(.require.php != null) | select(.version_normalized != null) | .version_normalized, .require.php' \
| sed -e '/dev/,+1d' -e '1~2 s/\..*//' -e '2~2 s/|.*$//' -e 's/[^0-9]*//' \
| cut -f1,2 -d'.' \
| awk 'NR%2{printf "%s ",$0;next;}1' \
| sort -Vru -k1,1 \
| sed '/^5 /d' \
| jq -Rcn '[inputs | split(" ") | {v:.[0], php:.[1]}]' \
| tee /tmp/versions.json
echo "matrix=$(cat /tmp/versions.json)" >> "$GITHUB_OUTPUT"
```

You then can get that output to use in the matrix strategy

```sh
strategy:
    matrix:
        laravel: ${{ fromJson(needs.fetch_laravel_versions.outputs.matrix) }}
```

Workflow: https://github.com/KevinBatdorf/artisan-api/blob/main/.github/workflows/generate-commands.yml#L8
Example workflow run: https://github.com/KevinBatdorf/artisan-api/actions/runs/4755840332

I could probably PR this if you'd like, or otherwise maybe you want to customize it, etc feel free!

**Comment by jbrooksuk** [comment]
This is very cool! I hadn't thought about automating this away, but what a great idea.

I'd also love to get artisan.page upgraded to Nuxt v3 and then we can implement the API into a single place.

The other thing I'd like to do is versioned command endpoints `/10.x/cache_clear`. You could compare against other versions etc.

**Comment by jbrooksuk** [comment]
@KevinBatdorf fancy making a PR? :)

**Comment by KevinBatdorf** [comment]
> I'd also love to get artisan.page upgraded to Nuxt v3 and then we can implement the API into a single place.

I think you might have to port it rather than upgrade. If you do the migration I'll happily add the API routes 😎 or you could copy it from my repo too if you'd like.

I can also PR the above workflow stuff if you want.

**Comment by jbrooksuk** [comment]
Porting isn't a problem either. It'll mostly be a copy and paste (for the actual site code). The configuration changes will be the most annoying.

Could you PR the workflow separately, please?
