### ISSUE TITLE
Add sub-command navigation.

### ISSUE THREAD

**Issue by firebyou** [jbrooksuk/artisan.page#37]
For example, when selecting "php artisan make:xxx," every time you want to switch to another "make" command, you have to scroll back to the top of the screen, which is a poor user experience. I suggest adding a floating secondary navigation on the right side, specifically for the sub-commands under "make."

**Comment by jbrooksuk** [comment]
Not a bad shout. For now, I've merged https://github.com/jbrooksuk/artisan.page/pull/33/ which makes the sidebar sticky, so you can at least see the commands while you look at other ones.

**Comment by firebyou** [comment]
Yea, add search function to the sidebar sticky.

**Comment by jbrooksuk** [comment]
You can press `/`, `Ctrl+k` or `⌘+k` to focus the search bar.
