### ISSUE TITLE
Create accordion H2, navigation left 

### ISSUE THREAD

**Issue by Grezor** [jbrooksuk/artisan.page#43]
Hello,

A small recommendation to improve the user interface is to add an accordion at the h2 level. When all the categories are open on the left, you need to scroll to the bottom to search for what you want.

`<h2 class="text-xl font-bold text-gray-900 dark:text-gray-500 snap-start" data-v-inspector="components/ArtisanBrowser.vue:12:11"> Commands <span class="text-xs text-gray-500 dark:text-gray-200" data-v-inspector="components/ArtisanBrowser.vue:14:13"> (214) </span></h2>`

![image](https://github.com/jbrooksuk/artisan.page/assets/38507456/dcafdea2-7005-4abd-bf6b-13ffe438e0b8)
![image](https://github.com/jbrooksuk/artisan.page/assets/38507456/d1f418bd-7a6e-4c31-9360-6bd6cd0f64c5)

-- Exemple result : 

![image](https://github.com/jbrooksuk/artisan.page/assets/38507456/809a7414-99f9-4648-abc8-1fb2a6f2a912)

**Comment by jbrooksuk** [comment]
You can use Cmd/Ctrl+K to search, which I think is better than hiding all commands by default.
