### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by EDDYMENS** [jbrooksuk/artisan.page#6]
Is there going to be some sort of versioning, so we know which version of LV a command is supported on?

**Comment by jbrooksuk** [comment]
Currently, we're only showing `8.x`. I'd like to include `7.x` and add a switcher too.

**Comment by EDDYMENS** [comment]
> Currently, we're only showing `8.x`. I'd like to include `7.x` and add a switcher too.

Got you! thanks for replying
